### ISSUE TITLE
What to do with GatorGradle version?

### ISSUE THREAD

**Issue by ullrichd21** [cmpsc-481-s22-m1/GatorConfig#46]
**What is the task**
We are taking this as an input but to my knowledge there is nothing to do with it? Some please advise.

**Describe the solution you'd like**
What do we do with this value? Put it in the YAML? What's the tag?

**Additional context**

**Comment by ullrichd21** [comment]
@Michionlion Please advise?

**Comment by Michionlion** [comment]
The version of GatorGradle is determined by the string on `build.gradle` after the `version` keyword.

**Comment by ullrichd21** [comment]
> The version of GatorGradle is determined by the string in `build.gradle` after the `version` keyword.

What is the keyword for the gatorgrader version then?

**Comment by Michionlion** [comment]
The GatorGrader version is specified in a different file, `config/gatorgrader.yml`, with the `version` key in the header.
